version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: "npm start"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/my-new-app
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-new-app:/app
      - node_modules:/app/node_modules  

    working_dir: /app
    command: "npm run dev"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

volumes:
  mongo_data:
  node_modules:  
